# Generated by Django 4.1 on 2024-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
